### ISSUE TITLE
PdfFormatProvider import exception - unable to cast PdfArray to PdfDictionary

### ISSUE THREAD

**Issue by rmed1na** [telerik/document-processing-sdk#7]
Trying to do a PDF Import

Code snippet:

_PdfFormatProvider provider = new PdfFormatProvider();
 using (var stream = File.OpenRead(fullPath))
 {
       RadFixedDocument document = provider.Import(stream);
 }_

Where "fullPath" is my local path to my PDF (e.g.: C:\user\source\file.pdf). The following exception is thrown right at the import statement:

`'Unable to cast object of type 'Telerik.Windows.Documents.Fixed.FormatProviders.Pdf.Model.Types.PdfArray' to type 'Telerik.Windows.Documents.Fixed.FormatProviders.Pdf.Model.Types.PdfDictionary'.'`

**Comment by velikovmartin** [comment]
Hi Rolando,

Thank you for the feedback. This behavior seems to be related to document parsing inability. In order to deeper investigate it we will need the document causing this exception. Please check the [Support Options](https://docs.telerik.com/devtools/document-processing/introduction#support-options) we are providing.
