### ISSUE TITLE
Trial installation messes up nuget directory \ToolboxNuGetPackages

### ISSUE THREAD

**Issue by rmed1na** [telerik/document-processing-sdk#8]
After installing the trial for the telerik document processing, the following errors comes up with .NET Core 3.1 projects:

- The local source 'C:\Program Files (x86)\Progress\ToolboxNuGetPackages' doesn't exist.
- Unable to find fallback package folder 'C:\Program Files (x86)\Progress\ToolboxNuGetPackages'.

This is whenever I try to restore nuget packages, clean solution, build or rebuild solution. Checking out the directory it indeed is missing the folder and just has lot of Telerik new folders.

Important thing to notice is that the project with the issue doesn't use any Telerik software. It was just a separate project with no relation to the one that does have the trial.

**Comment by TanyaDimitrova** [comment]
It seems you hit a known issue about a missing NuGet fallback folder while installing the Telerik version 2021.1.122. Please refer to the following thread and feel free to use the solution suggested here: [Projects fail to build in .NET Core/.NET 5.0 while restoring NuGet](https://www.telerik.com/forums/new-e127f0fe0ef0). Please, excuse us for the inconvenience caused. 

The issue should be fixed with the latest uploaded version. In case you are still facing it, please share more details on what version you are installing and which exactly package is used.

I hope this helps. Let me know if you have further difficulties.
